"""add pengajuan and mealplan

Revision ID: 7782a9c8cb86
Revises: e2ef515b9954
Create Date: 2026-03-06 02:24:10.778781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7782a9c8cb86'
down_revision: Union[str, Sequence[str], None] = 'e2ef515b9954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengajuans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alasan', sa.String(), nullable=False),
    sa.Column('bukti', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='statuspengajuan'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_tanggal'), 'meal_plans', ['tanggal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_plans_tanggal'), table_name='meal_plans')
    op.drop_table('pengajuans')
    # ### end Alembic commands ###
